services:
  - type: web
    name: render-subnet-router
    env: docker
    region: oregon
    plan: starter
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_VERSION
        value: 1.56.1
      - key: ADVERTISE_ROUTES
        value: 10.0.0.0/8,100.0.0.0/8,::/0
    disk:
      name: tailscale-state
      mountPath: /var/lib/tailscale
      sizeGB: 1

